
app:
  version: search-feat/swagger-31
  timestamp: Fri Aug  7 03:32:19 UTC 2020

server:
  port: 8090
  compression:
    enabled: true
    mime-types: application/json

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${database.host}:5432/${database.database}?ApplicationName=StarterApi
    username: ${database.username}
    password: ${database.password}
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jmx:
    enabled: false
  groovy:
    template:
      check-template-location: false
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"

security:
  login:
    # Entry below is temporary and is not advised to be here
    # but for simplicity and compliance to the requirement that it must be configurable
    # then this will do. Override via environment variable if needed.
    username: admin
    password: '{noop}password123'
    role: ADMIN
exam:
  validation:
    postal:
      email-pattern: '[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}'
      url: 'https://api.postcodes.io/postcodes/:postcode'

  data:
    source:
      url: 'https://collections.museumsvictoria.com.au/api/search'

  swagger:
    info:
      description:
      title:
      version:
      termsOfService:
      contact:
        name:
        url:
        email:
      license:
      licenseUrl:
    host: ''
